name: 'enforce-collaborator-action'
description: 'Enforces current user to be a repo collaborator'
branding:
  icon: stop-circle
  color: red
inputs:
  github_token:  
    description: 'github token'
    required: true
outputs:
  is_collaborator: 
    description: 'Is the current user a repo collaborator'
runs:
  using: 'node20'
  main: 'dist/index.js'
