name: 'actions-enforce-maintainer'
description: 'Enforces current workflow to be run by repo maintainer'
inputs:
  github_token:  
    description: 'github token'
    required: true
outputs:
  is-maintainer: 
    description: 'Is the current user a repo maintainer'
runs:
  using: 'node20'
  main: 'dist/index.js'
