on: [push]

jobs:
  enforce-collaborator-action:
    runs-on: ubuntu-latest
    name: A job to check current user is a repo collaborator
    steps:
      - name: Repo Collaborator Check
        id: enforce-collaborator-action
        uses: tommaso-borgato/enforce-collaborator-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output
        run: 'echo "Is collaborator: ${{ steps.enforce-collaborator-action.outputs.is-collaborator }}"'
